package com.spring.wefit.command;

import java.sql.Timestamp;
import java.util.Date;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class NoticeBoardVO {
	/*
	  CREATE TABLE "SPRINGWEFIT"."NOTICEBOARD" 
	   (	"NBNUM" NUMBER(10,0) NOT NULL ENABLE, 
		"MNUM" NUMBER(20,0) NOT NULL ENABLE, 
		"NBTITLE" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
		"NBCONTENT" VARCHAR2(2000 BYTE), 
		"NBIMAGE1" VARCHAR2(50 BYTE), 
		"NBREALIMAGE1" VARCHAR2(50 BYTE), 
		"NBLOOKCOUNT" NUMBER(20,0) DEFAULT 0 NOT NULL ENABLE, 
		"NBIMAGECOUNT" NUMBER(2,0) NOT NULL ENABLE, 
		"NBREGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
		 CONSTRAINT "PK_NOTICEBOARD" PRIMARY KEY ("NBNUM")
	  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "SYSTEM"  ENABLE
	   ) SEGMENT CREATION IMMEDIATE 
	  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "SYSTEM" ;
	  */
	
	private int nbNum;
	private int memberNum;
	private String nbTitle;
	private String nbContent;
	private String nbImage1;
	private String nbRealImage1;
	private int nbLookCount;
	private int nbImageCount;
	private Date nbRegDate;
	
	
	private String memberNick;
	private int nbReplyCount;
	private int nbReportCount;
	
	
	
	
	

}
