package com.spring.wefit.command;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class NoticeLikelyVO {
	
	/*
	 * CREATE TABLE "SPRINGWEFIT"."NOTICELIKELY" 
   (	"NBNUM" NUMBER(10,0) NOT NULL ENABLE, 
	"MEMBERNUM" NUMBER(20,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
	 */
	
	private int nrNum;
	private int memberNum;
	

}
