package com.spring.wefit.command;

import java.sql.Timestamp;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
public class NoticeReplyVO {
	
	/* CREATE TABLE "SPRINGWEFIT"."NOTICEREPLY" 
	   (	"NRNUM" NUMBER(10,0) NOT NULL ENABLE, 
		"NBNUM" NUMBER(10,0) NOT NULL ENABLE, 
		"NRCONTENT" VARCHAR2(200 BYTE) NOT NULL ENABLE, 
		"MNUM" NUMBER(20,0) NOT NULL ENABLE, 
		"NRREGDATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
		 CONSTRAINT "PK_NOTICEREPLY" PRIMARY KEY ("NRNUM")
	  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "SYSTEM"  ENABLE
	   ) SEGMENT CREATION IMMEDIATE 
	  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
	  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
	  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
	  TABLESPACE "SYSTEM" ;*/
	
	private int nrNum;
	private int nbNum;
	private String nrContent;
	private int memberNum;
	private Timestamp nrRegDate;
	
	private String memberNick;
	
	
	
	
	

}
